workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
      variables:
        ENV: hml
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        ENV: prd
    - when: always

include:
  - template: Jobs/SAST-IaC.gitlab-ci.yml
  - component: gitlab.com/components/opentofu/validate-plan-apply@0.24.0
    inputs:
      version: 0.24.0
      opentofu_version: 1.7.2
      state_name: "${ENV}"

variables:
  TF_CLI_ARGS_plan: "-var-file=envs/${ENV}.tfvars"

stages:
  - validate
  - test
  - build
  - deploy

kics-iac-sast:
  needs: []

apply:
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "main"'
      when: manual
